### ISSUE TITLE
Trial #1 Resulting Issues, Considerations, and To-Do

### ISSUE THREAD

**Issue by laurahspencer** [RobertsLab/project-geoduck-oa#2]
-  [x] 1. Header tanks need to be “bled” to maintain temperature: **Cort installed small hose/valve; need to test this.**
-  [x] 2. Float valve on Header Tank #1 sticks: **Cort installed new valve.**
-  [x] 3. Pump on Header Tank #2 makes a high-pitched whirring sound; **Cort replaced it but kept it as back-up.**
-  [x] 4. Need to try to keep pumps dry; when draining the header tanks we should use a hose directed into the drain. Need to build a flex hose with a union.
-  [ ] 5. Dispensette often has air bubbles, OR possibly 50ul is too little to accurately dispense.
-  [x] 6. Temperature meter did not seemingly function on the “automatic” setting, but did respond to manual adjustments. 
-  [ ] 7. Pressure in the CO2 line is important for effectiveness of dosing; too high and the solenoid will fail, too low and the pH set point cannot be reached. We were unable to maintain a 7.0 pH in Trial #1. Need to both dial in appropriate CO2 pressure and relay settings (cycle time, on time). **Doug/Rick ordered a regulator for the CO2 line; will likely install on Wednesday 3/2** 
-  [ ] 8. Try to find Y hose connectors to avoid uneven crimping of culture tank hoses
-  [ ] 9. Consider installing small valves before hose barbs on each culture tank line to be able to control individual flow (while dropping tanks, etc.)
-  [ ] 10. Consider taking daily algae counts from culture tanks to confirm equal concentrations
-  [x] 11. Venturian injector on Tank #2 reconnected, but need to confirm that the functions/does not leak; it was disconnected due to it making a noise unlike the other injector.
-  [x] 12. Finish the drainage plumbing (from culture tanks)
-  [x] 13. Need lab pen for water chemistry sample bottles 
-  [x] 14. Acquire replacement pH probe

**Comment by sr320** [comment]
@laurahspencer re 14 - what pH probe needs replacement?

**Comment by laurahspencer** [comment]
I was mistaken- it was the connection between the new pH probe and the
digital device that I was referring to, which we received yesterday & which
Hollie has already assembled.

Cheers,
Laura

**Comment by hputnam** [comment]
#7. We have the regulator but will see how the pH holds over the weekend before installing. pH has been holding in the tanks from the afternoon of 03 March to the afternoon of 04 March.
